spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=rdjishnupriyan
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
